---

- hosts: all

  become: yes
  become_method: sudo

  pre_tasks:

    - name: gather facts
      setup:
        gather_subset:
          - 'all'

    - name: debug print facts
      debug:
        var: ansible_facts

    - name: set rhel family
      set_fact:
        huit_os_family: 'rhel'
        huit_os_major_version: "{{ ansible_facts['distribution_major_version'] }}"
        huit_os_version: "{{ ansible_facts['distribution_version'] }}"
      when: ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'CentOS'

    - name: set debian family
      set_fact:
        huit_os_family: 'deb'
        huit_os_major_version: "{{ ansible_facts['distribution_major_version'] }}"
        huit_os_version: "{{ ansible_facts['distribution_version'] }}"
      when: ansible_facts['os_family'] == 'Ubuntu' or ansible_facts['os_family'] == 'Debian'

  tasks:

    - name: install selected roles
      include_role:
        name: '{{ item }}' 
      loop: '{{ role_name }}'
      loop_control: 
        huit_os_family: '{{ huit_os_family }}'
