---
# tasks file for example-role
#

# Example that prints the loopback address and gateway for each host
- debug:
    msg: System {{ inventory_hostname }} is RHEL 
  when:  ansible_facts['huit_os_family'] == 'rhel'
